name: Document improvement
title: "Docs: some description"
description: Feedback on documentation, including errors and ideas
labels: ["documentation"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 描述问题或主题
    validations:
      required: true

  - type: textarea
    id: improve
    attributes:
      label: 需做出的修改
    validations:
      required: true
